config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, session: { sign_in: 'login'}
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :likes
  resources :dislikes
  resources :messages
  resources :friendships
  resources :charges do
    collection do
     
      #post :stripe_response
    end
  end
 match '/stripe_response', to: 'charges#stripe_response', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :replies, dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	belongs_to :post
	mount_uploader :image, ImageUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
   belongs_to :member   
   belongs_to :friend, class_name: "Member"
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :likeable, polymorphic: true
	belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:login]
  # model associations
    validates :mobile_no, uniqueness: true
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :replies, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :send_messages, class_name: "Message", :foreign_key=> 'sender_id'
    has_many :receive_messages, class_name: "Message", :foreign_key=> 'receiver_id'
    
    has_many :friendships, class_name: "Friendship", :foreign_key=> 'friend_id'
    has_many :invite_friendships, class_name: "Friendship", :foreign_key=> 'member_id'
    #has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :invite_friendships, source: :member
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  # Class methods
  def login=(login)
    @login = login
  end

  def login
    @login || self.mobile_no || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["mobile_no = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:mobile_no) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :member
	has_many :comments,  dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	has_attached_file :image, styles: { large: "400x400", medium: "200x200>", 
	thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :dislikes, as: :dislikeable
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	belongs_to :member
	belongs_to :post
	belongs_to :comment
	has_many :likes, as: :likeable, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_member!
  
  def new
    @like = Like.new
  end

  def create
    if params[:post_id]
			@post = Post.find_by_id(params[:post_id])
			@like = @post.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		  #@like = @post.likes.new(member_id: current_member.id)
		elsif params[:comment_id]
			@comment = Comment.find_by_id(params[:comment_id])
			@like = @comment.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		elsif params[:reply_id]
      @reply = Reply.find_by_id(params[:reply_id])
      @like = @reply.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		end

		@like.like = params[:like]
    respond_to do |format|
      if @like.save
        format.html{redirect_to posts_path}
    	  format.js{}
    	end
    end
  end
  
  def destroy

  	if params[:post_id]
      @post = Post.find_by_id(params[:post_id])
    	@like = @post.likes.find_by_member_id(current_member.id)

    elsif params[:comment_id]
  	  @comment = Comment.find(params[:comment_id])
  	  @like = @comment.likes.find_by_member_id(current_member.id)

	  elsif params[:reply_id]
		  @reply = Reply.find(params[:reply_id])
		  @like = @reply.likes.find_by_member_id(current_member.id)
		end
    @like.like = params[:like]
    respond_to do |format|
		  if @like.destroy
		    format.html{redirect_to posts_path}
			  format.js
		  end
	  end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_member!
  def index
   	@members = Member.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# def count_like(Post)
	# 	Post.likes.where(like: true).count
	# end

	# def count_dislike(Post)
	# 	Post.likes.where(like: false).count
	# end
		

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div id="new_message"></div>
<div class="col-md-4">
  <div class="well">
    <table class="table">
      <th>contacts</th>
      <tr>
        <th>sr no.</th>
        <th>email</th>
        <th>create message</th>
      </tr>

      <%@members.each_with_index do |member, index| %>
        <% if member !=(current_member)%>
          <tr>
            <td><%= index = "#{index+1}" %></td><ul>
            <td><%= member.email %></td>
            <td><%= link_to  'Message', new_message_path(receiver_id: member.id)%>
            </td>
          
            <% if Friendship.where(friend_id: current_member.id, member_id: member.id | current_member.id, member_id: member.id, accepted: false).empty?
              #current_member.invite_friendships.where(friend_id: member.id).empty?  %>
              <td><%= link_to  'send Request', friendships_path(friend_id: member.id, member_id: current_member.id), method: :post%></td>
            <% elsif current_member.invite_friendships.where(friend_id: member.id, accepted: false).present? %>
              <td>Request sent</td>
            <% elsif current_member.invite_friendships.where(friend_id: current_member.id, accepted: false).present?%>
              <%current_member.requested_friendships.each do |request| %>
              <td><%= link_to  'Aceept Request', friendship_path(friend_id: member.id, accepted: true), method: :patch %></td>
               <td><%= link_to  'Reject Request', friendship_path(friend_id: member.id), method: :destroy %></td> 
              <%end%> 
             <%end%>
          </tr>
        <%end%>
      <%end%>
    </table>
  </div>
</div>

app/views/welcome/new.html.erb
<form action="/your-server-side-code" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_mEfPmZ2dXZ4iCu1GGfvWq6qk"
    data-amount="999"
    data-name="Demo Site"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>