config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, session: { sign_in: 'login'}
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :likes
  resources :dislikes
  resources :messages
  resources :friendships
  resources :charges do
    collection do
     
      #post :stripe_response
    end
  end
 match '/stripe_response', to: 'charges#stripe_response', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :replies, dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	belongs_to :post
	mount_uploader :image, ImageUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
   belongs_to :member   
   belongs_to :friend, class_name: "Member"
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :likeable, polymorphic: true
	belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:login]
  # model associations
    validates :mobile_no, uniqueness: true
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :replies, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :send_messages, class_name: "Message", :foreign_key=> 'sender_id'
    has_many :receive_messages, class_name: "Message", :foreign_key=> 'receiver_id'
    
    has_many :friendships, class_name: "Friendship", :foreign_key=> 'friend_id'
    has_many :invite_friendships, class_name: "Friendship", :foreign_key=> 'member_id'
    #has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :invite_friendships, source: :member
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  # Class methods
  def login=(login)
    @login = login
  end

  def login
    @login || self.mobile_no || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["mobile_no = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:mobile_no) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :member
	has_many :comments,  dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	has_attached_file :image, styles: { large: "400x400", medium: "200x200>", 
	thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :dislikes, as: :dislikeable
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	belongs_to :member
	belongs_to :post
	belongs_to :comment
	has_many :likes, as: :likeable, dependent: :destroy
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  protect_from_forgery with: :null_session
  def index
  end
  def new
    @charge = Charge.new
  end

  def create
   
    Stripe.api_key = "sk_test_FPBhmFiCuqecJroPOgdSIiXW"
    @amount = 5000

    customer = Stripe::Customer.create(:email => params[:stripeEmail],
    :source => params[:stripeToken])

    charge = Stripe::Charge.create(:name => params[:name], :brand =>params[:brand], :customer => params[:customer], :funding => params[:funding], :customer_id => params[:customer])

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def stripe_response
    Stripe.api_key = "sk_test_FPBhmFiCuqecJroPOgdSIiXW"
    token = params[:stripeToken]
   
    # debugger
    # @customers = customers.select do |c|
    #   c.email.eql?(params[:stripeEmail])
    #   if @customers.present?
    #     customer = @customers.first
    #   else
    #     customer = Stripe::Customer.create( :source => token, :email =>params[:stripeEmail] )
    #   end
    # end
    #@charge = Stripe::Charge.create(charge_params)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_member!
  
  def new
    @like = Like.new
  end

  def create
    if params[:post_id]
			@post = Post.find_by_id(params[:post_id])
			@like = @post.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		  #@like = @post.likes.new(member_id: current_member.id)
		elsif params[:comment_id]
			@comment = Comment.find_by_id(params[:comment_id])
			@like = @comment.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		elsif params[:reply_id]
      @reply = Reply.find_by_id(params[:reply_id])
      @like = @reply.likes.where(member_id: current_member.id)
			@like = @like.first_or_create(member_id: current_member.id)
		end

		@like.like = params[:like]
    respond_to do |format|
      if @like.save
        format.html{redirect_to posts_path}
    	  format.js{}
    	end
    end
  end
  
  def destroy

  	if params[:post_id]
      @post = Post.find_by_id(params[:post_id])
    	@like = @post.likes.find_by_member_id(current_member.id)

    elsif params[:comment_id]
  	  @comment = Comment.find(params[:comment_id])
  	  @like = @comment.likes.find_by_member_id(current_member.id)

	  elsif params[:reply_id]
		  @reply = Reply.find(params[:reply_id])
		  @like = @reply.likes.find_by_member_id(current_member.id)
		end
    @like.like = params[:like]
    respond_to do |format|
		  if @like.destroy
		    format.html{redirect_to posts_path}
			  format.js
		  end
	  end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!
  respond_to :html, :js
  before_action :set_post, only: [:edit, :show, :update,:destroy]

	def index
    @posts = Post.all
	end

	def new
		@post = current_member.posts.new
	end

	def create
    post = current_member.posts.create(post_params)
    redirect_to posts_path
  end

  def edit
  end

  def update
  	respond_to do |format|
  	  if @post.update(post_params)
	      format.html {redirect_to posts_path}
		    format.js{}
	    end
  	end
  end

  def show
  end

  def destroy
  	respond_to do |format|
  	  if @post.destroy
		    format.html {redirect_to posts_path}
			  format.js{}
			end
  	end
  end

	protected
	def post_params
		params.require(:post).permit(:content, :image)
	end

	def set_post
		@post = Post.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# def count_like(Post)
	# 	Post.likes.where(like: true).count
	# end

	# def count_dislike(Post)
	# 	Post.likes.where(like: false).count
	# end
		

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <!-- <strong>$5.00</strong>! --></h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto"></script>
<% end %>

app/views/likes/create.js.erb
<% if @like.likeable_type == "Post" %>
	<% if @like.like == true %>
		$("#like-post-<%= @post.id %>").html("<%= j link_to "unlike(#{@post.likes.where(like: true).count})", like_path(@post.id, 'post_id': @post.id), method: :delete, remote: true %>");
		$("#dislike-post-<%= @post.id%>").html("<%= j link_to "dislike(#{@post.likes.where(like: false).count})", likes_path('post_id': @post.id, 'like': false), method: :post, remote:  true%>");
	<% else %>
		$("#like-post-<%= @post.id%>").html("<%= j link_to "like(#{@post.likes.where(like: true).count})", likes_path('post_id': @post.id, 'like': true), method: :post, remote:  true%>");
		$("#dislike-post-<%= @post.id %>").html("<%= j link_to "dislike(#{@post.likes.where(like: false).count})", like_path(@post.id, 'post_id': @post.id), method: :delete, remote: true %>");
	<% end %>
<% elsif @like.likeable_type == "Comment" %>
  <% if @like.like ==true %>
    $("#like-comment-<%= @comment.id %>").html("<%= j link_to "unlike(#{@comment.likes.where(like: true).count})", like_path(@comment.id, 'comment': @comment.id), method: :delete, remote: true %>");
		$("#dislike-comment-<%= @comment.id%>").html("<%= j link_to "dislike(#{@comment.likes.where(like: false).count})", likes_path('comment_id': @comment.id, 'like': false), method: :post, remote:  true%>");
	<%else%>
	  $("#like-comment-<%= @comment.id%>").html("<%= j link_to "like(#{@comment.likes.where(like: true).count})", likes_path('comment_id': @comment.id, 'like': true), method: :post, remote:  true%>");
		$("#dislike-comment-<%= @comment.id %>").html("<%= j link_to "dislike(#{@comment.likes.where(like: false).count})", like_path(@comment.id, 'comment_id': @comment.id), method: :delete, remote: true %>");
  <%end%>

<% elsif @like.likeable_type == "Reply" %>
  <% if @like.like ==true %>
    $("#like-reply-<%= @reply.id %>").html("<%= j link_to "unlike(#{@reply.likes.where(like: true).count})", like_path('reply': @reply.id), method: :delete, remote: true %>");
		$("#dislike-reply-<%= @reply.id%>").html("<%= j link_to "dislike(#{@reply.likes.where(like: false).count})", likes_path('reply': @reply.id, 'like': false), method: :post, remote:  true%>");
	<%else%>
	  $("#like-comment-<%= @reply.id%>").html("<%= j link_to "like(#{@reply.likes.where(like: true).count})", likes_path('reply_id': @reply.id, 'like': true), method: :post, remote:  true%>");
		$("#dislike-comment-<%= @reply.id %>").html("<%= j link_to "dislike(#{@reply.likes.where(like: false).count})", like_path('reply_id': @reply.id), method: :delete, remote: true %>");
  <%end%>
<%end%>

app/views/likes/destroy.js.erb
<% if @like.likeable_type == "Post" %>
  $("#like-post-<%= @post.id%>").html("<%= j link_to "like(#{@post.likes.where(like: true).count})", likes_path('post_id': @post.id, 'like': true), method: :post, remote:  true%>");
  $("#dislike-post-<%= @post.id%>").html("<%= j link_to "dislike(#{@post.likes.where(like: false).count})", likes_path('post_id': @post.id, 'like': false), method: :post, remote:  true%>");
<% elsif @like.likeable_type == "Comment" %>
  $("#like-comment-<%= @comment.id%>").html("<%= j link_to "like(#{@comment.likes.where(like: true).count})", likes_path('comment_id': @comment, 'like': true), method: :post, remote:  true%>");
  $("#dislike-comment-<%= @comment.id%>").html("<%= j link_to "dislike(#{@comment.likes.where(like: false).count})", likes_path('comment_id': @comment.id, 'like': false), method: :post, remote:  true%>");
<% elsif @like.likeable_type == "Reply" %>
  $("#like-reply-<%= @reply.id%>").html("<%= j link_to "like(#{@reply.likes.count})", likes_path('reply_id': @reply), method: :post, remote:  true%>");  
<%end%>

app/views/posts/_add_new_post.html.erb
<div id="@post.id">
  <p><%= indexplus ="Post #"%></p>
    <!-- <div id="first"><%#= @post.name %></td> -->
    <p><%=image_tag (@post.image) %></p><br>
    <p><%= @post.content %></p>  
    <p><%= link_to 'comment', new_post_comment_path(@post)%></p>
    <p><%= link_to '', edit_post_path(@post), :class=>"glyphicon glyphicon-pencil", data: {id: @post.id}, remote: true %></p>
    <p><%= link_to '', post_path(@post), method: :delete,
      data: { confirm: 'Are you sure?' }, :class=>"glyphicon glyphicon-remove-sign", remote: true%></p>
</div>

app/views/posts/_form.html.erb
<div class="col-md-4 col-md-offset-3">
  <div class="well">

    <%= form_for (@post ? @post : post), html: { multipart: true }, remote: true do |f| %>
      <div class="form-group">
        <%= f.label         :upload_image %>
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.label      :post%>
        <%= f.text_field :content%>
      </div>
      <div class = "col-md-offset-5">
        <div class="form-group">
          <%= f.submit "Submit", class: "btn btn-primary btn-sm"%>
        </div>
    <%end%>
  </div>
</div>

app/views/posts/create.js.erb
$("#post-<%=@post.id%>").prepend("<%=j render('add_new_post')%>");
// $("#new_post > div").remove();

app/views/posts/destroy.js.erb
$("div#post-<%=@post.id%>").remove();

app/views/posts/edit.html.erb
<%= render 'form' %>

 
     

app/views/posts/edit.js.erb
$('#new_post').html("<%= j render('form') %>");

app/views/posts/index.html.erb
<div id="new_post"></div>
<div id="all-posts">
  <div class="row">
    
    <% @posts.each_with_index do |post, index| %>
      <div class="col-sm-6 col-md-4, col-md-offset-3">
        <div class="thumbnail">
          <div class="caption">
            <div id="post-<%=post.id%>">
      		    <span><%= image_tag (post.image.url(:medium)) %></span><br>
              <span><%= post.content %></span>
      		    <span><%= link_to 'comment', new_post_comment_path(post), remote: true%></span>
              <!--check current_member id for post -->
              <% if post.member.eql?(current_member)%>
                <span><%= link_to '', edit_post_path(post), :class=>"glyphicon glyphicon-pencil", data: {id: post.id}, remote: true %></span>
                <span><%= link_to '', post_path(post), method: :delete, :class=>"glyphicon glyphicon-remove-sign", remote: true%></span>
              <%end%>
               <!--like and dislike links for post-->
                <span id="like-post-<%= post.id%>"><%= link_to "like(#{ post.likes.where(like: true).count})", likes_path(post_id: post, like: true), method: :post, remote: true%></span>
                <span id="dislike-post-<%= post.id%>"><%= link_to "dislike(#{post.likes.where(like: false).count})", likes_path(post_id: post, like: false), method: :post, remote: true%></span> 
              <div id="post-comment-<%= post.id%>"></div>
            </div>
          
            <% post.comments.each_with_index do |comment, index| %>
	            <div class="thumbnail">
	              <div class="caption">
                  <div id="comment-<%=comment.id%>">
                    <span><%= image_tag (comment.image.url) %></span><br>
	                  <span><%= comment.content %></span>
          	        <span><%= link_to 'reply', new_post_comment_reply_path(post, comment),  remote: true%></span>
                    <!--checking current_member id for comment -->
                    <% if comment.member_id.eql?(current_member.id) %>
                      <span  id="edit-comment-<%=comment.id%>"><%= link_to  '', edit_post_comment_path(post, comment), :class=>"glyphicon glyphicon-pencil", remote: true%></span>
                      <span><%= link_to '', post_comment_path(post, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"glyphicon glyphicon-remove-sign", remote: true%></span>
                    <%end%>
                    <!-- like and dislike links for post.comment -->
                    <span id="like-comment-<%= comment.id%>"><%= link_to "like(#{comment.likes.where(like: true).count})", likes_path(comment_id: comment, like: true), method: :post, remote:  true%></span>
                    <span id="dislike-comment-<%= comment.id%>"><%= link_to "dislike(#{comment.likes.where(like: false).count})", likes_path(comment_id: comment, like: false), method: :post, remote: true%></span> 
                    <div id="post-comment-<%= comment.post.id%>"></div>
                    <div id="post-comment-reply-<%= comment.id%>"></div>
                  </div>

                  <% comment.replies.each_with_index do |reply, index| %>
                    <div class="thumbnail">
                      <div class="caption">
                        <div id="reply-<%=reply.id%>">
                          <span><%= reply.content%></span>
                          <!-- checking current_member id for reply -->
                          <%if reply.member_id.eql?(current_member.id)%>
                            <span ><%= link_to  '',  edit_post_comment_reply_path(comment.post, comment, reply), :class=>"glyphicon glyphicon-pencil", remote: true%></span>
                            <span><%= link_to '',  post_comment_reply_path(post, comment, reply), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"glyphicon glyphicon-remove-sign", remote: true %></span>
                          <%end%>
                          <!-- like and dislike links for Reply -->
                          <span id="like-reply-<%= reply.id%>"><%= link_to "like(#{reply.likes.count})", likes_path(reply_id: reply), method: :post, remote: true%>
                          </span>

                          <span id="dislike-reply-<%= reply.id%>"><%= link_to "dislike(#{reply.likes.count})", likes_path(reply_id: reply), method: :post, remote: true%></span>
                          <div id="post-comment-reply-<%=comment.id%>"></div>
                        </div>
                      </div>
                    </div>
                  <%end%>

                </div>
              </div>
            <%end%>

          </div>
        </div>
      </div>
    <%end%>

  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/new.js.erb
$("#new_post").html("<%= j render('form') %>");

app/views/posts/update.js.erb
$('#new_post').html("<%= j render('form') %>");
$("#new_post > div").remove();