config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :members, session: { sign_in: 'login'}
  resources :posts do 
    resources :comments do
      resources :replies
    end
  end
  resources :likes
  resources :dislikes
  resources :messages
  resources :friendships
  resources :charges do
    collection do
     
      #post :stripe_response
    end
  end
 match '/stripe_response', to: 'charges#stripe_response', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	has_many :replies, dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	belongs_to :post
	mount_uploader :image, ImageUploader
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/friendship.rb
class Friendship < ApplicationRecord
   belongs_to :member   
   belongs_to :friend, class_name: "Member"
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :likeable, polymorphic: true
	belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:login]
  # model associations
    validates :mobile_no, uniqueness: true
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :replies, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :send_messages, class_name: "Message", :foreign_key=> 'sender_id'
    has_many :receive_messages, class_name: "Message", :foreign_key=> 'receiver_id'
    
    has_many :friendships, class_name: "Friendship", :foreign_key=> 'friend_id'
    has_many :invite_friendships, class_name: "Friendship", :foreign_key=> 'member_id'
    #has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :invite_friendships, source: :member
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  # Class methods
  def login=(login)
    @login = login
  end

  def login
    @login || self.mobile_no || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["mobile_no = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:mobile_no) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :member
	has_many :comments,  dependent: :destroy
	has_many :likes, as: :likeable, dependent: :destroy
	has_attached_file :image, styles: { large: "400x400", medium: "200x200>", 
	thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :dislikes, as: :dislikeable
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	belongs_to :member
	belongs_to :post
	belongs_to :comment
	has_many :likes, as: :likeable, dependent: :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# def count_like(Post)
	# 	Post.likes.where(like: true).count
	# end

	# def count_dislike(Post)
	# 	Post.likes.where(like: false).count
	# end
		

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Social Application</a>
      </div>
      <ul class="nav navbar-nav">
        <% if current_member %>
          <li class="active"><a href="/posts"> All Posts</a></li>
          <li><a href="/posts/new">New Post</a></li>
          <li><%= link_to "Message", messages_path(current_member.id)%></li>
          <li><a href="/charges/new">Create Charge</a></li>
          <li><%= link_to "", new_charge_path(current_member.id)%></li>

        <%else%>
          <li class="active"><a href="/">Home</a></li>
        <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_member %>
          <%= link_to destroy_member_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out logout-btn"> Logout</span> 
          <%end%>
        <%else%>
          <li><a href="/members/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/members/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <%end%>
      </ul>
    </div>
  </nav>
  <%= yield %>
 </body>
</html>